### ISSUE TITLE
[FsprgStoreParameters toURL] returns URL that doesn't work

### ISSUE THREAD

**Issue by vslavik** [FastSpring/FsprgEmbeddedStoreMac#10]
In code like this (taken from the provided examples):

```
FsprgStoreParameters *parameters = [FsprgStoreParameters parameters];
[parameters setOrderProcessType:kFsprgOrderProcessDetail];
[parameters setStoreId:@"poedit" withProductId:@"poedit-pro"];
```

the `toURL` method returns an URL such as https://sites.fastspring.com/poedit/product/poedit-pro — i.e. an HTTPS URL. But the FastSpring store cannot server this page via HTTPS and demands HTTP access — the page shown says this:

```
Secure Connection Not Allowed

This resource may not be accessed with a secure (https) connection.
Use a normal connection method (http) instead.
```

So the officially documented method of opening the store in a browser doesn't work. This should either return a http:// URL or — and that would be my preference — sites.fastspring.com should just serve the same content over both HTTP and HTTPS.

To be honest, this whole _Secure Connection Not Allowed_ thing seems rather weird to me and doesn't make much sense to me. Especially now that Google is pushing for HTTPS-only web, the first store page really should be HTTPS...

**Comment by karstenBriksoft** [comment]
Apple is enforcing App Transport Security on macOS. Using the standard kFsprgOrderProcessDetail will choose http as protocol will fail with an error message and the page will not load. Using kFsprgOrderProcessInstant instead will choose https, allowing the page to be loaded. 
The only other way around this problem is explicitly enabling http in the app (see http://stackoverflow.com/a/30732693/440657).
A much simpler solution would be to remove the test to use http and always use https.
