### ISSUE TITLE
Store image assets don't load properly with App Transport Security on El Capitan

### ISSUE THREAD

**Issue by bewebste** [FastSpring/FsprgEmbeddedStoreMac#19]
The problem occurs when compiling against the 10.11 SDK with Xcode 7, which enables Apple's new App Transport Security, disabling non-secure HTTP loads by default. 

https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/?cm_mc_uid=07998743765214248868379&cm_mc_sid_50200000=1442426628

While the page itself loads OK, since it's connecting to https://sites.fastspring.com, some of the images in the page do not load. In the example screenshot, the icon for the app being sold is missing, as well as icons in the "Order Now" button, the icon by the language selection menu, etc.

![screen shot 2015-09-25 at 5 48 09 pm](https://cloud.githubusercontent.com/assets/15607/10114862/9dbdce9c-63ad-11e5-8cac-60592ed4d40b.png)

This also causes error messages like the following to be printed to the console, indicating that there are connections being blocked by ATS.

2015-09-25 17:45:51.839 PowerPhotos[15923:21862984] NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)

This can be worked around by adding the NSAppTransportSecurity and NSAllowArbitraryLoads keys in your Info.plist file, but it should be made possible to load the embedded store without needing to make any exceptions in the Info.plist.

**Comment by steiger** [comment]
Hi @bewebste 

Sorry for our late reply. We looked into it and it happens because cloudfront.net hasn't switched to SHA256, yet. We don't want to over-promise on behalf of AWS but we expect Amazon to have things switched to SHA256 by the end of October. See also https://aws.amazon.com/security/security-bulletins/aws-to-switch-to-sha256-hash-algorithm-for-ssl-certificates/ and https://forums.aws.amazon.com/thread.jspa?messageID=678295#jive-message-679300.

As you already mentioned, you can work around it in the meantime by adding keys in your Info.plist files. This should help:

```xml
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSExceptionDomains</key>
        <dict>
            <key>cloudfront.net</key>
            <dict>
                <key>NSExceptionRequiresForwardSecrecy</key>
                <false/>
                <key>NSIncludesSubdomains</key>
                <true/>
            </dict>
        </dict>
    </dict>
```

Best regards,
Lars
