### ISSUE TITLE
Use ARC

### ISSUE THREAD

**Issue by ghost** [FastSpring/FsprgEmbeddedStoreMac#3]
Most new apps use ARC. It would be great to be able to put these files into a new Mac app and have them Just Work™, instead of having to manually disable ARC for each of them individually, which is currently required for using these in an ARC app.

I'm open to converting the files to ARC myself and submitting a pull request (assuming there's no technical restrictions from doing so). Would such a pull request be welcome?

**Comment by DivineDominion** [comment]
+1 Any progress on that front from your side?

**Comment by steiger** [comment]
No, sorry. But you could embed it via CocoaPods (https://cocoapods.org/pods/FsprgEmbeddedStoreMac) if you don't want to do manual work.

**Comment by vslavik** [comment]
> Pull requests are always welcome.

Are they? I'm seeing quite a few here, some of them trivial and solving real issues (such as building with Xcode 7). Without exception, they are not only not merged long after being created, but not even commented on by FastSpring. What's the point of spending time on PRs then?

By the way, ARC in particular could be easily cherry-picked from the forks graph (if you don't want to do spend the required two minutes converting the project in Xcode)...

Honestly, would be good to know if you guys abandoned the SDK entirely (this one, the answer is sadly obvious for the zombie Windows ones) or are planning to do at least minimal maintenance.

**Comment by steiger** [comment]
Hi @vslavik 

Thanks for letting us know about the pull requests. We will monitor them more closely in the future.

We are in the process of updating our core platform capabilities and have been conservative in making changes to the SDK so that we can revise it based on new capabilities.

In the case of ARC, we have concerns about making changes that are not backwards compatible with the thousands of active integrations into our platform.  Providing ARC via CocoaPods allows developers to use ARC if they want, without forcing it on the whole community.

Lars
